const express=require('express');const helmet=require('helmet');const cors=require('cors');const config=require('./config');const {checkDatabase,pool}=require('./db');
const app=express();app.set('trust proxy',1);app.use(helmet());app.use(cors());app.use(express.json({limit:'1mb'}));
app.get('/api/couple-space/health',async(_req,res)=>{try{await checkDatabase();res.json({success:true,data:{database:'connected'}})}catch{res.status(503).json({success:false,msg:'数据库不可用'})}});
app.use('/api/couple-space/auth',require('./routes/auth'));app.use('/api/couple-space/resources',require('./routes/resources'));app.use('/api/couple-space',require('./routes/profile'));
app.get('/api/couple-space/avatars',require('./auth').requireAuth,async(req,res)=>{if(!req.userRow.couple_id)return res.json({success:true,data:[]});const [rows]=await pool.query('SELECT couple_id,male_url,female_url FROM avatars WHERE couple_id=?',[req.userRow.couple_id]);res.json({success:true,data:rows.map(x=>({_id:String(x.couple_id),coupleId:String(x.couple_id),male:x.male_url||'',female:x.female_url||''}))});});
app.patch('/api/couple-space/avatars',require('./auth').requireAuth,async(req,res)=>{if(!req.userRow.couple_id)return res.status(409).json({success:false,msg:'请先绑定情侣'});const male=req.body.male===undefined?null:String(req.body.male),female=req.body.female===undefined?null:String(req.body.female);await pool.query(`INSERT INTO avatars(couple_id,male_url,female_url) VALUES(?,?,?) ON DUPLICATE KEY UPDATE male_url=COALESCE(VALUES(male_url),male_url),female_url=COALESCE(VALUES(female_url),female_url)`,[req.userRow.couple_id,male,female]);res.json({success:true,data:null});});
app.get('/api/couple-space/dashboard',require('./auth').requireAuth,async(req,res)=>{const id=req.userRow.couple_id;if(!id)return res.json({success:true,data:{counts:{album:0,countdown:0,orders:0}}});const [[a],[c],[o]]=await Promise.all([pool.query('SELECT COUNT(*) count FROM albums WHERE couple_id=?',[id]),pool.query('SELECT COUNT(*) count FROM countdowns WHERE couple_id=?',[id]),pool.query('SELECT COUNT(*) count FROM orders WHERE couple_id=? AND status="pending"',[id])]);res.json({success:true,data:{counts:{album:a[0].count,countdown:c[0].count,orders:o[0].count}}});});
app.use((_req,res)=>res.status(404).json({success:false,msg:'接口不存在'}));app.use((err,_req,res,_next)=>{console.error(err);res.status(err.status||500).json({success:false,msg:err.status?err.message:'服务器内部错误'});});
if(require.main===module){checkDatabase().then(()=>app.listen(config.port,config.host,()=>console.log(`Couple Space API listening on ${config.host}:${config.port}`))).catch(e=>{console.error('MySQL connection failed:',e.message);process.exit(1)});}module.exports=app;
